Issues #61 おすすめ記事表示機能の実装
jack-app/jackweb3 pull request #63
Opened 2024-05-03 19:29 UTC by morita-koki

## 関連issue

#61 

## やったこと
- おすすめ記事表示機能の実装
- OGPイメージで表示できるよう修正
- (scssのフォーマットがうまくできていなかったのを修正)

## 表示画面
- PC
![スクリーンショット 2024-05-04 4 23 13](https://github.com/jack-app/jackweb3/assets/83483589/41482562-ce5f-4bb8-9009-e70e2e993289)

- SP
![スクリーンショット 2024-05-04 4 22 51](https://github.com/jack-app/jackweb3/assets/83483589/da53da00-be93-40da-a35c-cc57b34662f7)

2024-05-18 04:00 UTC, yutteee requested changes
ちょっと修正多くなってしまいますがお願いします！

2024-05-18 04:00 UTC, yutteee commented on src/features/SuggestArticleList/presentations/index.module.scss
余白について細かい修正をお願いします🙇

主に以下が修正の理由です
- 基本8px単位で余白を当てる様にしている
- 関連情報同士の余白を小さくする
- 視線の誘導(z型に目を通しやすい様にする)

2024-06-02 13:06 UTC, morita-koki commented on src/pages/blog/[id]/index.tsx
> +  const suggestArticles = (await getSuggestArticles()) as ArticleItemProps[];
変えました

2024-06-02 13:06 UTC, morita-koki commented on src/pages/blog/[id]/index.tsx
> +// };
消しました

2024-06-02 13:14 UTC, morita-koki commented on .prettierrc.js
セミコロンfalseにしたのはミスです。

parser: typescriptがついてると.scssのファイルにフォーマットが当たらないんだけど、、、自分だけ???

2024-06-02 13:35 UTC, morita-koki commented on src/utils/useGetArticles.ts
直しました

2024-06-02 13:41 UTC, morita-koki commented on src/features/SuggestArticleList/presentations/index.module.scss
うい

2024-06-02 13:56 UTC, morita-koki commented on src/screens/BlogArticle/index.module.scss
> +  gap: 30px;
うい

2024-06-02 13:57 UTC, morita-koki commented on .prettierrc.js
修正しました

2024-06-03 15:10 UTC, yutteee reviewed
デザイン部分の修正をお願いします！

2024-06-03 15:10 UTC, yutteee commented on src/screens/BlogArticle/index.module.scss
pcサイズでおすすめ記事の上に余白がないので修正して欲しいです！
![スクリーンショット 2024-06-04 0 08 45](https://github.com/jack-app/jackweb3/assets/83484258/79f20e68-e043-4f66-9d31-d765e5e2e3dc)

2024-06-03 15:10 UTC, yutteee commented on src/ui/ArticleItem/index.module.scss
幅縮めると崩れるので修正して欲しいです！

![スクリーンショット 2024-06-04 0 07 55](https://github.com/jack-app/jackweb3/assets/83484258/0abf8cdf-47a6-452a-ba48-a8a7102cfe9b)

2024-06-06 13:08 UTC, morita-koki commented on src/screens/BlogArticle/index.module.scss
done

2024-06-06 13:28 UTC, Riku-0801 approved these changes

2024-06-06 13:28 UTC, morita-koki commented on src/ui/ArticleItem/index.module.scss
done

2024-06-06 17:56 UTC, yutteee approved these changes
修正した部分あるので確認お願いします！

2024-06-06 17:56 UTC, yutteee commented on src/pages/blog/[id]/index.tsx
> +
hooksを削除しました。
pagesに入ってるものはページとしてNext.jsに認識されてしまってビルドが通らなくなるためです

2024-06-06 17:56 UTC, yutteee commented on src/ui/SuggestArticleList/index.module.scss
> +
モバイル~pcでgapが指定されてなかったのを修正しました

2024-06-06 17:56 UTC, merged